[tasks.image]
command = "docker"
args = ["build", "-t", "mysqlpinger", "."]

[tasks.tag]
script = [
	"docker tag mysqlpinger ymgyt/mysqlpinger:${VERSION:? required}",
	"docker tag mysqlpinger ymgyt/mysqlpinger:latest",
	"docker image ls --filter 'reference=ymgyt/mysqlpinger'"
]

[tasks.push]
script = [
	"docker push ymgyt/mysqlpinger:${VERSION:? required}"
]

[tasks.install]
command = "cargo"
args = ["install", "--path", "."]

[tasks.version]
script = [
	"echo ${VERSION:? required}"
]

[tasks.precommit]
script = [
    "cargo fmt",
	"cargo clippy"
]

[tasks.publish]
dependencies = [
	"version",
	"image",
	"tag",
	"push",
	"install"
]
